### PR TITLE
Supporting Windows

### PR DESCRIPTION
**Pull request by kazu-yamamoto**
Replacing #25.

### CODE REVIEW

**Comment by kazu-yamamoto** [comment]
@BernardoGomesNegri Please review this PR.

- Is `winsock.h` necessary in `picotls.c`?
- Are the header modifications of `picotls.h` and `fusion.c` necessary?

**Comment by BernardoGomesNegri** [comment]
No, winsock.h nor winsock2.h are necessary in picotls.c, but ws2tcpip.h is.
It is not necessary in picotls.h, but it is necessary in fusion.c.
I don't have much experience in programming C on Windows, I am sorry.

**Comment by kazu-yamamoto** [comment]
@BernardoGomesNegri Now `quic` can be built on Windows. Thanks. However, the test does not pass at all. Does the test pass on your environment?

**Comment by BernardoGomesNegri** [comment]
My tests do fail, but for a weirder reason:
`Network\QUIC\Socket.hs:4:1: error:
    Could not load module `UnliftIO.Exception'
    It is a member of the hidden package `unliftio-0.2.20'.
.\Network\QUIC\Packet\Number.hs:13: failure in expression `encodePacketNumber 0xabe8bc 0xac5c02 == (0x5c02,2)'
expected: True
 but got:
          ^
          <interactive>:27:1: error:
              Variable not in scope: encodePacketNumber :: t0 -> t1 -> (a0, b0)`
The QuickCheck library seems to be running the tests before all the library is done building.

**Comment by kazu-yamamoto** [comment]
@BernardoGomesNegri If doctest is the source of your problem, check spec only. For instance, `cabal test spec`.

**Comment by BernardoGomesNegri** [comment]
Well, "cabal test spec" just opens some ports, accesses the certificate files, transfers some data, then hangs indefinitely.
The client program also will always fail with "ConnectionTimeout" regardless of where I point it. I am investigating why that is the case.

**Comment by kazu-yamamoto** [comment]
So, receiving in the client side might have a problem.

**Comment by kazu-yamamoto** [comment]
https://stackoverflow.com/questions/47383826/winsock2-recvfrom-function-ends-with-error-10022-invalid-argument

Isn't the client socket bound?

**Comment by kazu-yamamoto** [comment]
OK. I think I understand the situation. `recvfrom` is called before `sendto` is used because of racing between the `sender` and `reader` threads.

I will cherry-pick three commits to `master` and use this PR to fix the bug.

**Comment by kazu-yamamoto** [comment]
The race was fixed on this branch. However, the test suite does not display the results at all, sigh.

**Comment by BernardoGomesNegri** [comment]
I have some information: I added some print lines that say "about to recv" when it is about to call any of the recv functions, "sent data" when it sends a packet data and "got something" when something is written to the socket. I ran both the client and the servers and asked the client to connect to the server. Here is what I got from the client:
```
"about to recv"
"sent data"
"got something"
"about to recv"
"got something"
"about to recv"
"sent data"
"sent data"
"sent data"
"sent data"
"got something"
"about to recv"```

**Comment by BernardoGomesNegri** [comment]
The client socket is being connected, at least on my machine.

**Comment by kazu-yamamoto** [comment]
@Mistuke Sorry for bothering you. But I think we need your help. `master` of `quic` library now can be built on Windows but the test suite are not passed. I would like to ask basic questions:

- Which version of GHC offers stable network functionality including `-threaded` and lightweight threads? (CI now using GHC 8.8. GHC 8.10.2 has a linker problem.)
- Suppose that we provides two lightwieght threads. One reads data from a UDP socket and the other writes data to the socket. Does this code work on Windows?

**Comment by igrep** [comment]
@kazu-yamamoto I've added tons of debug code with its example debug log at https://github.com/igrep/quic/commit/863a8d522889bbb5fa48a8a6bfd2e7de0fd5708f .
(NOTE: The example log file (example.log) contains not-yet committed changes to the network package. Tell me if you need!)
According to the log, the server looks stalled.

And I'll send you packets' log captured by Wireshark.

**Comment by Mistuke** [comment]
Oh looks like I missed this, I'll take a look on Monday :)

**Comment by Mistuke** [comment]
> @Mistuke Sorry for bothering you. But I think we need your help. `master` of `quic` library now can be built on Windows but the test suite are not passed. I would like to ask basic questions:
> 
> * Which version of GHC offers stable network functionality including `-threaded` and lightweight threads? (CI now using GHC 8.8. GHC 8.10.2 has a linker problem.)

Both should work fine, what's the linker error with 8.10.2? However over the years we did have scheduler fixes. 

> * Suppose that we provides two lightwieght threads. One reads data from a UDP socket and the other writes data to the socket. Does this code work on Windows?

With mio you'll need threaded and the I/O calls need to be interruptable so they don't block the native thread handling the requests. In the end something else can interfere with the thread as the mio i/o manager doesn't really integrate with the networking. 

For winio this should work for both threaded and non-threaded (I'm hoping to finish support during the holidays).

But in short, yes it should work with `-threaded` given the constraints above. Which tests are failing?

**Comment by Mistuke** [comment]
> According to the log, the server looks stalled.

So something has probably blocked the I/O thread. The more useful log here is compiling with `-debug -rtsopts` and run with `+RTS -Ds` to dump the scheduler output which should say why it stalled. Pipe this to a file

**Comment by kazu-yamamoto** [comment]
> But in short, yes it should work with -threaded given the constraints above. Which tests are failing?

A normal communication of QUIC cannot carry out at all on Windows at this moment. So, all test cases based on QUIC communication fail.

**Comment by igrep** [comment]
New log thanks to kazu and Mitsuke's advice: https://github.com/kazu-yamamoto/quic/commit/042c26c190d0ea4a0ea261b8df24e3fba04dcefe

**Comment by kazu-yamamoto** [comment]
@Mistuke Is this rumor true?

https://stackoverflow.com/questions/59779711/problems-using-udp-sockets-bound-to-the-same-port-on-windows?rq=1

If Windows cannot handle a listen UDP socket and connected UDP sockets on the same port correctly, I need to give up supporting Windows.

**Comment by kazu-yamamoto** [comment]
I confirmed that this rumor is true on my quic library.

**Comment by BernardoGomesNegri** [comment]
How unfortunate. It would probably require a big rewrite. We tried out best. Thank you for finding out what is the problem, and happy Christmas Eve.

**Comment by kazu-yamamoto** [comment]
A MS guy says to me that this is true and there is no way to change this behavior. So, I need to take the approach of a single wildcard socket on Windows, sigh.

**Comment by Mistuke** [comment]
> @Mistuke Is this rumor true?
> 
> https://stackoverflow.com/questions/59779711/problems-using-udp-sockets-bound-to-the-same-port-on-windows?rq=1
> 
> If Windows cannot handle a listen UDP socket and connected UDP sockets on the same port correctly, I need to give up supporting Windows.

Must say I've never tried this so I don't know, the documentation on `SO_REUSEADDR` seems to indicate that it should be possible https://docs.microsoft.com/en-us/windows/win32/winsock/using-so-reuseaddr-and-so-exclusiveaddruse but the behavior of bounded sockets on the same protocol is non-deterministic.

**Comment by Mistuke** [comment]
> New log thanks to kazu and Mitsuke's advice: [042c26c](https://github.com/kazu-yamamoto/quic/commit/042c26c190d0ea4a0ea261b8df24e3fba04dcefe)

Thanks, that does indicate that it's blocked waiting on an external call, so the deadlock isn't a GHC issue, it looks like it ran out of work to do.

**Comment by Mistuke** [comment]
For it to have a chance of working you need to specify `SO_REUSEPORT` though, I don't see that being set anywhere?
image

**Comment by kazu-yamamoto** [comment]
`SO_REUSEPORT` is for multicast. So, I guess that it is not relating to this issue.

And the MS guy said that our interpretation of Windows behavior is correct. So, I'm now planning to change the server architecture of `quic` on Windows.

Thank you, @Mistuke, for helping me always. Happy holiday!

**Comment by Mistuke** [comment]
Cheers, happy holidays to you too!

**Comment by kazu-yamamoto** [comment]
I would like to close this issue. Window stuff should be discussed in another issue in the future.

**Comment by kazu-yamamoto** [comment]
The client side works well now.  This means that `MVar` & `forkIO` hack against `killThread` works well on the client side.

However, the server side does not work well. It seems to me that the hack does not work. And Windows behaves strange when multiple UDP connected sockets exist. So, the server side support is now a long plan.

**Pull request closed without merging**
