### PR TITLE
Compile on Windows

### PR DESCRIPTION
**Pull request by BernardoGomesNegri**
Hello,

this pull request makes it so the library can be compiled on Windows. I changed all references to GHC.Event to point to a new module: Network.QUIC.Event. In case the target OS is not Windows, this module simply re-exports GHC.Event. In case it is Windows, I created a small timer module, which, while it does create new threads, works as a drop-in replacement for the timer functions in GHC.Event. This change was needed because GHC.Event is not avaliable on Windows.
Many C header files which are not avaliable on Windows were replaced with the corresponding Windows header files, all with preprocessor guards to make sure the code, if not compiled on Windows, stays the same. There are also some new C definitions that should act as a direct replacement for their POSIX equivalents.

### CODE REVIEW

**Review by kazu-yamamoto — CHANGES_REQUESTED** [review]
Thanks you for supporting Windows. To make things simpler, I would like to ask you:

- Please send another PR only for `withSocketsDo`. This will be quicly merged.
- Please send another PR only for `Network.QUIC.Event`. This will be quicly merged.
- For C bits stuff, I would like to ask which you prefer:
  - Your approach: modification to `picotls.c` and `picotls.h` should be merged into the upstream (the `picotls` project). I guess that `gettimeofday` is not necessary because Haskell `quic` does not use related functions. Just comment out is good enough.
  - Approach based on #21: even if Windows is running on x86_64, `cryptonite` is used. This code is slow a bit but you don't have to care about C bits at all.

**Comment by BernardoGomesNegri** [comment]
I created the withSocketsDo pull request in #27 and for Network.QUIC.Event in #26.
I would prefer merging my changes into the picotls project. I will submit the pull request to them. However, I think it is a good idea to keep gettimeofday() so this project's version of picotls remains the same as the one in upstream.

**Comment by BernardoGomesNegri** [comment]
I submitted the picotls changes in https://github.com/h2o/picotls/pull/375. However, the picotls in this project is different than the one in upstream. The one in upstream does not have the supplement_new function that is used here nor any references to the "uint" type.

**Comment by BernardoGomesNegri** [comment]
I commented out gettimeofday and everything else that depends on it.

**Comment by kazu-yamamoto** [comment]
It seems to me that you modified the comment style of `picotls.c` which makes the merge jobs really hard. I made a simpler PR (#30), so I close this.

**Pull request closed without merging**
